// Copyright 2014 The Bazel Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package net.starlark.java.syntax

import com.google.common.base.Ascii
import com.google.common.base.Preconditions
import com.google.common.collect.ImmutableList
import com.google.errorprone.annotations.FormatMethod
import net.starlark.java.spelling.SpellChecker
import kotlin.collections.ArrayList
import kotlin.collections.HashMap
import kotlin.collections.HashSet
import kotlin.collections.Iterable
import kotlin.collections.MutableList
import kotlin.collections.MutableMap
import kotlin.collections.MutableSet

/**
 * The Resolver resolves each identifier in a syntax tree to its binding, and performs other
 * validity checks.
 * 
 * 
 * When a variable is defined, it is visible in the entire block. For example, a global variable
 * is visible in the entire file; a variable in a function is visible in the entire function block
 * (even on the lines before its first assignment).
 * 
 * 
 * Resolution is a mutation of the syntax tree, as it attaches binding information to Identifier
 * nodes. (In the future, it will attach additional information to functions to support lexical
 * scope, and even compilation of the trees to bytecode.) Resolution errors are reported in the
 * analogous manner to scan/parse errors: for a StarlarkFile, they are appended to `StarlarkFile.errors`; for an expression they are reported by an SyntaxError.Exception exception.
 * It is legal to resolve a file that already contains scan/parse errors, though it may lead to
 * secondary errors.
 */
class Resolver private constructor(
    errors: MutableList<SyntaxError?>,
    module: Module,
    options: FileOptions,
    docCommentsMap: MutableMap<String?, DocComments?>?
) : NodeVisitor() {
    // TODO(adonovan):
    // - use "keyword" (not "named") and "required" (not "mandatory") terminology everywhere,
    //   including the spec.
    // - move the "no if statements at top level" check to bazel's check{Build,*}Syntax
    //   (that's a spec change), or put it behind a FileOptions flag (no spec change).
    /** Scope discriminates the scope of a binding: global, local, etc.  */
    enum class Scope {
        /** Binding is local to a function, comprehension, or file (e.g. load).  */
        LOCAL,

        /** Binding is non-local and occurs outside any function or comprehension.  */
        GLOBAL,

        /** Binding is local to a function, comprehension, or file, but shared with nested functions.  */
        CELL,

        /** Binding is an implicit parameter whose value is the CELL of some enclosing function.  */
        FREE,

        /** Binding is predeclared by the application (e.g. glob in Bazel).  */
        PREDECLARED,

        /** Binding is predeclared by the core (e.g. None).  */
        UNIVERSAL;

        override fun toString(): String {
            return Ascii.toLowerCase(super.toString())
        }
    }

    /**
     * A Binding is a static abstraction of a variable. The Resolver maps each Identifier to a
     * Binding.
     */
    open class Binding private constructor(
        scope: Scope?,
        index: Int,
        bindingId: Int,
        isSyntactic: Boolean,
        first: Identifier
    ) {
        @kotlin.jvm.JvmField
        private var scope: Scope?

        // index within frame (LOCAL/CELL), freevars (FREE), or module (GLOBAL)
        @kotlin.jvm.JvmField
        private val index: Int

        // index within the set of all bindings in the program
        private val bindingId: Int

        // True if there is at least one binding occurrence in the resolved syntax tree;
        // false for bindings that are generated by successfully matching a name in Module#resolve.
        //
        // In practice, during normal use of the interpreter on a file, this is only false for
        // universals and predeclareds. However, it can also be false for globals if they are made
        // available via the module without being bound by the current syntax. This happens in
        // particular in the REPL, where the same Module is shared across multiple input syntax trees.
        private val isSyntactic: Boolean

        // If isSyntactic is true, the first binding occurrence of this symbol.
        // Otherwise, the first occurrence of this symbol (which must be non-binding).
        private val first: Identifier

        init {
            this.scope = scope
            this.index = index
            this.bindingId = bindingId
            this.isSyntactic = isSyntactic
            this.first = first
        }

        /**
         * Returns the first binding occurrence of this symbol, or if there is none, the first
         * non-binding occurrence.
         */
        fun getFirst(): Identifier {
            return first
        }

        /** Returns whether any binding occurrence of this symbol appears in the syntax tree.  */
        fun isSyntactic(): Boolean {
            return isSyntactic
        }

        /** Returns the name of this binding's identifier.  */
        fun getName(): String {
            return first.getName()
        }

        /** Returns the scope of the binding.  */
        fun getScope(): Scope? {
            return scope
        }

        /**
         * Returns the index of a binding within its function's frame (LOCAL/CELL), freevars (FREE), or
         * module (GLOBAL).
         */
        fun getIndex(): Int {
            return index
        }

        /** Returns the sequence number of the binding within the set of all bindings in the program.  */
        fun getBindingId(): Int {
            return bindingId
        }

        override fun toString(): String {
            val declaredAt =
                if (isSyntactic)
                    first.getStartLocation().toString()
                else
                    if (scope == Scope.UNIVERSAL || scope == Scope.PREDECLARED)
                        "<builtin>" // e.g., on a previous input of the REPL
                    else
                        "<previously defined>"
            return String.format("%s[%d] %s @ %s", scope, index, first.getName(), declaredAt)
        }
    }

    private fun newBinding(scope: Scope?, index: Int, isSyntactic: Boolean, first: Identifier): Binding {
        return Resolver.Binding(scope, index, nextBindingId++, isSyntactic, first)
    }

    /** A [Binding] for a variable of a list or dict comprehension.  */
    class ComprehensionBinding private constructor(index: Int, bindingId: Int, first: Identifier, node: Comprehension) :
        Binding(
            Scope.LOCAL, index, bindingId,  /* isSyntactic= */true, first
        ) {
        // Used only for determining the range of locations encompassing the comprehension's lexical
        // scope. Can be replaced with {start0, end0, start1, end1} positions if we switch to a
        // non-AST-based evaluation model.
        private val node: Comprehension

        init {
            this.node = node
        }

        /** Returns true if the given location falls within the scope of the comprehension.  */
        fun inScope(loc: Location): Boolean {
            if (loc.file() != node.getStartLocation().file()) {
                return false
            }
            // Following Python3, the first for clause of a comprehension is resolved outside the
            // comprehension block. All the other loops are resolved in the scope of their own bindings,
            // permitting forward references.
            val for0 = node.getClauses().get(0) as Comprehension.For
            val iterable0 = for0.getIterable()
            if (loc.compareTo(iterable0.getStartLocation()) >= 0
                && loc.compareTo(iterable0.getEndLocation()) < 0
            ) {
                return false
            }
            if (loc.compareTo(node.getStartLocation()) >= 0 && loc.compareTo(node.getEndLocation()) < 0) {
                return true
            }
            return false
        }
    }

    private fun newComprehensionBinding(
        index: Int, first: Identifier, node: Comprehension
    ): ComprehensionBinding {
        return Resolver.ComprehensionBinding(index, nextBindingId++, first, node)
    }

    /** A Resolver.Function records information about a resolved function.  */
    class Function private constructor(
        name: String,
        loc: Location?,
        functionId: Int,
        numBindingsInFile: Int,
        params: ImmutableList<Parameter>,
        body: ImmutableList<Statement>?,
        hasVarargs: Boolean,
        hasKwargs: Boolean,
        numKeywordOnlyParams: Int,
        locals: MutableList<Binding?>,
        freevars: MutableList<Binding?>,
        globals: MutableList<String?>,
        mutationFreeAtTopLevel: Boolean
    ) {
        private val name: String?
        private val location: Location?
        private val functionId: Int

        // Used only for toplevel or expr-wrapping functions; set to -1 otherwise.
        private val numBindingsInFile: Int
        private val params: ImmutableList<Parameter>
        private val body: ImmutableList<Statement>?
        private val hasVarargs: Boolean
        private val hasKwargs: Boolean
        private val numKeywordOnlyParams: Int
        private val parameterNames: ImmutableList<String?>
        private val isToplevel: Boolean
        private val locals: ImmutableList<Binding?>
        private val cellIndices: IntArray
        private val freevars: ImmutableList<Binding?>
        private val globals: ImmutableList<String?> // TODO(adonovan): move to Program.
        @kotlin.jvm.JvmField
        private val mutationFreeAtTopLevel: Boolean

        init {
            this.name = name
            this.location = loc
            this.functionId = functionId
            this.numBindingsInFile = numBindingsInFile
            this.params = params
            this.body = body
            this.hasVarargs = hasVarargs
            this.hasKwargs = hasKwargs
            this.numKeywordOnlyParams = numKeywordOnlyParams

            val names = ImmutableList.builderWithExpectedSize<String?>(params.size)
            for (p in params) {
                names.add(p.getName())
            }
            this.parameterNames = names.build()

            this.isToplevel = name == "<toplevel>"
            this.locals = ImmutableList.copyOf<Binding?>(locals)
            this.freevars = ImmutableList.copyOf<Binding?>(freevars)
            this.globals = ImmutableList.copyOf<String?>(globals)
            this.mutationFreeAtTopLevel = mutationFreeAtTopLevel

            // Create an index of the locals that are cells.
            var ncells = 0
            val nlocals = locals.size
            for (i in 0..<nlocals) {
                if (locals.get(i).scope == Scope.CELL) {
                    ncells++
                }
            }
            this.cellIndices = IntArray(ncells)
            var i = 0
            var j = 0
            while (i < nlocals) {
                if (locals.get(i).scope == Scope.CELL) {
                    cellIndices[j++] = i
                }
                i++
            }
        }

        /**
         * Returns the name of the function. It may be "<toplevel>" for the implicit function that holds
         * the top-level statements of a file, or "<expr>" for the implicit function that evaluates a
         * single expression.
        </expr></toplevel> */
        fun getName(): String? {
            return name
        }

        /**
         * Returns the sequence number of the function within the set of functions in the program.
         * 
         * 
         * If this function is the toplevel function of a file or expression, its sequence number is
         * the highest function sequence number in the program.
         */
        fun getFunctionId(): Int {
            return functionId
        }

        /**
         * For the toplevel function of a file or the wrapper function of an expression, returns the
         * number of bindings in the file or expression. Otherwise, returns -1.
         */
        fun getNumBindingsInFile(): Int {
            return numBindingsInFile
        }

        /** Returns the value denoted by the function's doc string literal, or null if absent.  */
        fun getDocumentation(): String? {
            if (getBody()!!.isEmpty()) {
                return null
            }
            val first = getBody()!!.get(0)
            if (first !is ExpressionStatement) {
                return null
            }
            val expr = first.getExpression()
            if (expr !is StringLiteral) {
                return null
            }
            return expr.getValue()
        }

        /** Returns the function's local bindings, parameters first.  */
        fun getLocals(): ImmutableList<Binding?> {
            return locals
        }

        /**
         * Returns the indices within `getLocals()` of the "cells", that is, local variables of
         * thus function that are shared with nested functions. The caller must not modify the result.
         */
        fun getCellIndices(): IntArray {
            return cellIndices
        }

        /**
         * Returns the list of names of globals referenced by this function. The order matches the
         * indices used in compiled code.
         */
        fun getGlobals(): ImmutableList<String?> {
            return globals
        }

        /**
         * Returns the list of enclosing CELL or FREE bindings referenced by this function. At run time,
         * these values, all of which are cells containing variables local to some enclosing function,
         * will be stored in the closure. (CELL bindings in this list are local to the immediately
         * enclosing function, while FREE bindings pass through one or more intermediate enclosing
         * functions.)
         */
        fun getFreeVars(): ImmutableList<Binding?> {
            return freevars
        }

        /** Returns the location of the function's identifier.  */
        fun getLocation(): Location? {
            return location
        }

        /**
         * Returns the function's parameters, in "run-time order": non-keyword-only parameters,
         * keyword-only parameters, `*args`, and finally `**kwargs`. A bare `*`
         * parameter is dropped.
         */
        fun getParameters(): ImmutableList<Parameter> {
            return params
        }

        /**
         * Returns the effective statements of the function's body. (For the implicit function created
         * to evaluate a single standalone expression, this may contain a synthesized Return statement.)
         */
        // TODO(adonovan): eliminate when we switch to compiler.
        fun getBody(): ImmutableList<Statement>? {
            return body
        }

        /** Reports whether the function has an `*args` parameter.  */
        fun hasVarargs(): Boolean {
            return hasVarargs
        }

        /** Reports whether the function has a `**kwargs` parameter.  */
        fun hasKwargs(): Boolean {
            return hasKwargs
        }

        /**
         * Returns the number of the function's keyword-only parameters, such as `c` in `def f(a, *b, c, **d)` or `def f(a, *, c, **d)`.
         */
        fun numKeywordOnlyParams(): Int {
            return numKeywordOnlyParams
        }

        /** Returns the number of non-residual parameters.  */
        fun getNumNonResidualParameters(): Int {
            return params.size - (if (hasKwargs) 1 else 0) - (if (hasVarargs) 1 else 0)
        }

        /** Returns the number of ordinary (non-residual, non-keyword-only) parameters.  */
        fun getNumOrdinaryParameters(): Int {
            return params.size - (if (hasKwargs) 1 else 0) - (if (hasVarargs) 1 else 0) - numKeywordOnlyParams
        }

        /** Returns the names of the parameters. Order is as for [.getParameters].  */
        fun getParameterNames(): ImmutableList<String?> {
            return parameterNames
        }

        /**
         * isToplevel indicates that this is the <toplevel> function containing top-level statements of
         * a file.
        </toplevel> */
        // TODO(adonovan): remove this when we remove Bazel's "export" hack,
        // or switch to a compiled representation of function bodies.
        fun isToplevel(): Boolean {
            return isToplevel
        }

        /** Inverse of [Resolver.sawPossibleMutationAtTopLevel].  */
        fun isMutationFreeAtTopLevel(): Boolean {
            return mutationFreeAtTopLevel
        }
    }

    /**
     * A static abstraction of a Starlark [Module][net.starlark.java.eval.Module], that resolves
     * names to scope and type information rather than to dynamic Starlark values.
     * 
     * 
     * Contrast with [TypeTagger.LoadableModule], which is an abstraction of an already
     * compiled (and type-checked) module used by this one as a load dependency.
     * 
     * 
     * The [.resolve] API returns information about predefined variables, including those
     * provided by the interpreter itself ([Scope.UNIVERSAL]), the application ([ ][Scope.PREDECLARED]), and even evaluations that are considered to precede the current
     * environment ([Scope.GLOBAL] -- typically empty except for the REPL and unit tests). It
     * does *not* contain information about local symbols, or globals that are defined in the code
     * currently being resolved.
     * 
     * 
     * The [.resolveTypeConstructor] API returns type information used in static type
     * checking, but is not used directly in the resolver. It may include information about
     * user-defined types, i.e. types introduced as global symbols in the resolved code.
     */
    interface Module : TypeContext {
        /**
         * Resolves a name to a GLOBAL, PREDECLARED, or UNIVERSAL binding.
         * 
         * @throws Undefined if the name is not defined. The exception may contain a set of available
         * candidate names that are predefined symbols.
         */
        @Throws(Undefined::class)
        fun resolve(name: String?): Scope

        /**
         * Resolves a name to a corresponding type constructor.
         * 
         * @return null if the name is known but not a type constructor.
         * @throws Undefined if the name is not defined, as per [.resolve].
         */
        @Throws(Undefined::class)
        fun getTypeConstructor(name: String?): TypeConstructor?

        /**
         * An Undefined exception indicates a failure to resolve a top-level name. If `candidates`
         * is non-null, it provides the set of accessible top-level names, which, along with local
         * names, will be used as candidates for spelling suggestions.
         */
        class Undefined @kotlin.jvm.JvmOverloads constructor(
            message: String?,
            candidates: MutableSet<String?>? = null
        ) : Exception(message) {
            val candidates: MutableSet<String?>?

            init {
                this.candidates = candidates
            }
        }
    }

    /**
     * Represents a lexical block.
     * 
     * 
     * Blocks should not be confused with frames. A block generally (but not always) corresponds to
     * a syntactic element that may introduce variables; the variable is only accessible within the
     * block (and its descendants, unless shadowed). A frame is the place where the variable's content
     * will be stored, and is associated with the current enclosing function. Blocks are used to map
     * an identifier to the proper variable binding, whereas frames are used to ensure each binding
     * has a distinct slot of memory.
     * 
     * 
     * In particular, comprehension expressions have their own block but share the same underlying
     * frame as their enclosing function. This means that comprehension-local variables are not
     * accessible outside the comprehension, yet these variables are still stored alongside the other
     * local variables of the function.
     */
    private class Block(
        parent: Block?,
        syntax: Node?,
        frame: ArrayList<Binding?>,
        freevars: ArrayList<Binding?>?
    ) {
        private val parent: Block? // enclosing block, or null for tail of list
        var syntax: Node? // Comprehension, DefStatement/LambdaExpression, StarlarkFile, or null
        private val frame: ArrayList<Binding?> // accumulated locals of enclosing function

        // Accumulated CELL/FREE bindings of the enclosing function that will provide
        // the values for the free variables of this function; see Function.getFreeVars.
        // Null for toplevel functions and expressions, which have no free variables.
        private val freevars: ArrayList<Binding?>?

        // Bindings for names defined in this block.
        // Also, as an optimization, memoized lookups of enclosing bindings.
        private val bindings: MutableMap<String?, Binding?> = HashMap<String?, Binding?>()

        init {
            this.parent = parent
            this.syntax = syntax
            this.frame = frame
            this.freevars = freevars
        }
    }

    private val errors: MutableList<SyntaxError?>
    private val options: FileOptions
    private val module: Module

    // List whose order defines the numbering of global variables in this program.
    private val globals: MutableList<String?> = ArrayList<String?>()

    // A map from global variable names to their doc comments; added to by bind(); null if doc
    // comments for global variables are not being collected.
    private val docCommentsMap: MutableMap<String?, DocComments?>?

    // A cache of PREDECLARED, UNIVERSAL, and GLOBAL bindings queried from the module.
    private val toplevel: MutableMap<String?, Binding?> = HashMap<String?, Binding?>()

    // Linked list of blocks, innermost first, for functions and comprehensions and (finally) file.
    private var locals: Block? = null
    private var loopCount = 0
    private var nextBindingId = 0
    private var nextFunctionId = 0
    private var functionDepth = 0

    /**
     * A heuristic indicating whether the program being resolved contains any top-level expressions
     * that might mutate collections (e.g., function calls, index/dot writes, or augmented
     * assignments).
     * 
     * 
     * This is used by the runtime interpreter to safely optimize collection literals (lists,
     * dicts) into compact, immutable implementations to save memory. If this is false after resolving
     * the program, then any collection literals created when executing the program can be made
     * immutable at construction time.
     */
    private var sawPossibleMutationAtTopLevel: Boolean

    init {
        // Don't visit keyword args or dot expression fields -- those aren't symbols.
        this.skipNonSymbolIdentifiers = true

        this.errors = errors
        this.module = module
        this.options = options
        this.docCommentsMap = docCommentsMap
        this.sawPossibleMutationAtTopLevel = options.allowToplevelRebinding()
    }

    // Formats and reports an error at the start of the specified node.
    @FormatMethod
    private fun errorf(node: Node, format: String, vararg args: Any?) {
        errorf(node.getStartLocation(), format, *args)
    }

    // Formats and reports an error at the specified location.
    @FormatMethod
    private fun errorf(loc: Location?, format: String, vararg args: Any?) {
        errors.add(SyntaxError(loc, String.format(format, *args)))
    }

    /**
     * First pass: add bindings for all variables to the current block. This is done because symbols
     * are sometimes used before their definition point (e.g. functions are not necessarily declared
     * in order).
     */
    private fun createBindingsForBlock(stmts: Iterable<Statement>) {
        for (stmt in stmts) {
            createBindings(stmt)
        }
    }

    private fun createBindings(stmt: Statement) {
        when (stmt.kind()) {
            Statement.Kind.ASSIGNMENT -> {
                val assignStmt = stmt as AssignmentStatement
                createBindingsForLHS(assignStmt.getLHS(), assignStmt.getDocComments())
            }

            Statement.Kind.VAR -> {
                val varStmt = stmt as VarStatement
                bind(varStmt.getIdentifier(),  /* isLoad= */false, varStmt.getDocComments())
            }

            Statement.Kind.IF -> {
                val ifStmt = stmt as IfStatement
                createBindingsForBlock(ifStmt.getThenBlock())
                if (ifStmt.getElseBlock() != null) {
                    createBindingsForBlock(ifStmt.getElseBlock()!!)
                }
            }

            Statement.Kind.FOR -> {
                val forStmt = stmt as ForStatement
                createBindingsForLHS(forStmt.getVars(),  /* docComments= */null)
                createBindingsForBlock(forStmt.getBody())
            }

            Statement.Kind.DEF -> {
                val defStmt = stmt as DefStatement
                bind(defStmt.getIdentifier(),  /* isLoad= */false,  /* docComments= */null)
            }

            Statement.Kind.LOAD -> {
                val load = stmt as LoadStatement
                val names: MutableSet<String?> = HashSet<String?>()
                for (b in load.getBindings()) {
                    // Reject load('...', '_private').
                    val orig = b.getOriginalName()
                    if (orig.isPrivate() && !options.allowLoadPrivateSymbols()) {
                        errorf(orig, "symbol '%s' is private and cannot be imported", orig.getName())
                    }

                    // A load statement may not bind a single name more than once,
                    // even if options.allowToplevelRebinding.
                    val local = b.getLocalName()
                    if (names.add(local.getName())) {
                        bind(local,  /* isLoad= */true,  /* docComments= */null)
                    } else {
                        errorf(local, "load statement defines '%s' more than once", local.getName())
                    }
                }
            }

            Statement.Kind.TYPE_ALIAS -> {
                if (options.resolveTypeSyntax()) {
                    val typeStmt = stmt as TypeAliasStatement
                    bind(typeStmt.getIdentifier(),  /* isLoad= */false,  /* docComments= */null)
                }
            }

            Statement.Kind.EXPRESSION, Statement.Kind.FLOW, Statement.Kind.RETURN -> {}
        }
    }

    /** Calls [.bind] for appropriate identifiers of the LHS of an assignment.  */
    private fun createBindingsForLHS(lhs: Expression?, docComments: DocComments?) {
        for (id in Identifier.Companion.boundIdentifiers(lhs)) {
            bind(id,  /* isLoad= */false, docComments)
        }
    }

    /**
     * Extends the visit() traversal to the lhs of an assignment or for loop.
     * 
     * 
     * In particular, this sets bindings on identifiers appearing in read context, and asserts that
     * bindings are already set on identifiers appearing in write context.
     */
    private fun assign(lhs: Expression) {
        if (lhs is Identifier) {
            // Bindings are created by the first pass (createBindings).
            assertIsBound(lhs)
        } else if (lhs is IndexExpression) {
            visit(lhs)
        } else if (lhs is ListExpression) {
            for (elem in lhs.getElements()) {
                assign(elem)
            }
        } else if (lhs is DotExpression) {
            visit(lhs.getObject())
            // Do not visit the field. It is an identifier but does not correspond to a binding.
        } else {
            errorf(lhs, "cannot assign to '%s'", lhs)
        }
    }

    private fun assertIsBound(id: Identifier) {
        Preconditions.checkState(id.getBinding() != null, "%s expected to be bound", id.getName())
    }

    private fun assertIsNotBound(id: Identifier) {
        check(id.getBinding() == null) { String.format("%s expected to not be bound", id.getBinding()) }
    }

    override fun visit(id: Identifier) {
        // The visit() traversal should not reach any Identifier node more than once.
        // It also should not reach any binding occurrence of an Identifier at all -- those are set by
        // the first pass.
        assertIsNotBound(id)
        val bind = use(id)
        if (bind != null) {
            id.setBinding(bind)
            return
        }
    }

    override fun visit(node: ReturnStatement) {
        if (locals!!.syntax is StarlarkFile) {
            errorf(node, "return statements must be inside a function")
        }
        super.visit(node)
    }

    override fun visit(node: CallExpression) {
        // Conservative over-approximation: any top-level call (e.g., `list.append()`) could be a
        // mutation. Calls nested inside functions are safe to ignore, since if those functions are
        // eventually executed during load, it must be via a top-level call in the caller's file.
        if (functionDepth == 0) {
            sawPossibleMutationAtTopLevel = true
        }
        // validate call arguments
        var seenVarargs = false
        var seenKwargs = false
        var keywords: MutableSet<String?>? = null
        for (arg in node.getArguments()) {
            if (arg is Argument.Positional) {
                if (seenVarargs) {
                    errorf(arg, "positional argument may not follow *args")
                } else if (seenKwargs) {
                    errorf(arg, "positional argument may not follow **kwargs")
                } else if (keywords != null) {
                    errorf(arg, "positional argument may not follow keyword argument")
                }
            } else if (arg is Argument.Keyword) {
                val keyword = arg.getName()
                if (seenVarargs) {
                    errorf(arg, "keyword argument %s may not follow *args", keyword)
                } else if (seenKwargs) {
                    errorf(arg, "keyword argument %s may not follow **kwargs", keyword)
                }
                if (keywords == null) {
                    keywords = HashSet<String?>()
                }
                if (!keywords.add(keyword)) {
                    errorf(arg, "duplicate keyword argument: %s", keyword)
                }
            } else if (arg is Argument.Star) {
                if (seenKwargs) {
                    errorf(arg, "*args may not follow **kwargs")
                } else if (seenVarargs) {
                    errorf(arg, "multiple *args not allowed")
                }
                seenVarargs = true
            } else if (arg is Argument.StarStar) {
                if (seenKwargs) {
                    errorf(arg, "multiple **kwargs not allowed")
                }
                seenKwargs = true
            }
        }

        super.visit(node)
    }

    override fun visit(node: ForStatement) {
        if (locals!!.syntax is StarlarkFile) {
            errorf(
                node,
                "for loops are not allowed at the top level. You may move it inside a function "
                        + "or use a comprehension, [f(x) for x in sequence]"
            )
        }
        loopCount++
        visit(node.getCollection())
        assign(node.getVars())
        visitBlock(node.getBody())
        Preconditions.checkState(loopCount > 0)
        loopCount--
    }

    override fun visit(node: LoadStatement) {
        if (locals!!.syntax !is StarlarkFile) {
            errorf(node, "load statement not at top level")
        }
        // Skip super.visit: don't revisit local Identifier as a use.
    }

    override fun visit(node: FlowStatement) {
        if (node.getFlowKind() != TokenKind.PASS && loopCount <= 0) {
            errorf(node, "%s statement must be inside a for loop", node.getFlowKind())
        }
        super.visit(node)
    }

    override fun visit(node: Comprehension) {
        val clauses = node.getClauses()

        // Following Python3, the first for clause is resolved
        // outside the comprehension block. All the other loops
        // are resolved in the scope of their own bindings,
        // permitting forward references.
        val for0 = clauses.get(0) as Comprehension.For
        visit(for0.getIterable())

        // A comprehension defines a distinct lexical block in the same function's frame.
        // New bindings go in the frame but aren't visible to the parent block.
        pushLocalBlock(node, this.locals.frame, this.locals.freevars)

        for (clause in clauses) {
            if (clause is Comprehension.For) {
                createBindingsForLHS(clause.getVars(),  /* docComments= */null)
            }
        }
        for (i in clauses.indices) {
            val clause = clauses.get(i)
            if (clause is Comprehension.For) {
                if (i > 0) {
                    visit(clause.getIterable())
                }
                assign(clause.getVars())
            } else {
                val ifClause = clause as Comprehension.If
                visit(ifClause.getCondition())
            }
        }
        visit(node.getBody())
        popLocalBlock()
    }

    override fun visit(node: DefStatement) {
        assertIsBound(node.getIdentifier())
        // resolveFunction() recurses into the body.
        node.setResolvedFunction(
            resolveFunction(
                node,
                node.getIdentifier().getName(),
                node.getIdentifier().getStartLocation(),
                node.getParameters(),
                node.getReturnType(),
                node.getBody()
            )
        )
    }

    override fun visit(expr: LambdaExpression) {
        // resolveFunction() recurses into the body.
        expr.setResolvedFunction(
            resolveFunction(
                expr,
                "lambda",
                expr.getStartLocation(),
                expr.getParameters(),  /* returnType= */
                null,
                ImmutableList.of<Statement?>(ReturnStatement.Companion.make(expr.getBody()))
            )
        )
    }

    override fun visit(node: IfStatement) {
        if (locals!!.syntax is StarlarkFile) {
            errorf(
                node,
                "if statements are not allowed at the top level. You may move it inside a function "
                        + "or use an if expression (x if condition else y)."
            )
        }
        super.visit(node)
    }

    override fun visit(node: AssignmentStatement) {
        // Augmented assignments (e.g. `+=`) and non-pure bindings (e.g. index or dot writes) mutate
        // objects in-place. If nested inside a function body, they are safe to ignore.
        if (functionDepth == 0 && !sawPossibleMutationAtTopLevel) {
            sawPossibleMutationAtTopLevel = node.isAugmented() || !isPureBinding(node.getLHS())
        }
        visit(node.getRHS())

        // Disallow: [e, ...] += rhs
        // Other bad cases are handled in assign.
        if (node.isAugmented() && node.getLHS() is ListExpression) {
            errorf(
                node.getOperatorLocation(),
                "cannot perform augmented assignment on a list or tuple expression"
            )
        }

        if (node.getType() != null && options.resolveTypeSyntax()) {
            visit(node.getType())
        }
        assign(node.getLHS())
    }

    override fun visit(node: VarStatement) {
        assertIsBound(node.getIdentifier())
        if (options.resolveTypeSyntax()) {
            visit(node.getType())
        }
    }

    override fun visit(node: CastExpression) {
        if (options.resolveTypeSyntax()) {
            visit(node.getType())
        }
        visit(node.getValue())
    }

    override fun visit(node: IsInstanceExpression) {
        // TODO: #27848 - Restrict the types that can be used on the RHS of isinstance(); e.g. `list` or
        // `list | tuple` (or aliases resolving to those!) are allowed, but `list[int]` isn't,  since a
        // list can subsequently be mutated to add a non-int element. Probably needs to be done in
        // TypeTagger.
        errorf(node, "isinstance() is not yet supported")
    }

    override fun visit(node: TypeAliasStatement) {
        if (locals!!.syntax !is StarlarkFile) {
            errorf(node, "type alias statement not at top level")
        }

        if (options.resolveTypeSyntax()) {
            assertIsBound(node.getIdentifier())
            visit(node.getDefinition())
        }

        // TODO: #27370 - Bind the generic type params (`type Foo[S, T] = ...`). Will require creating
        // a new block for the RHS, since the type params don't leak outside the statement. (This
        // means extending the invariant of Block#syntax to allow include TypeAliasStatement.)
    }

    // Resolves a non-binding identifier to an existing binding, or null.
    private fun use(id: Identifier): Binding? {
        val name = id.getName()

        // Locally defined in this function, comprehension,
        // or file block, or an enclosing one?
        var bind = lookupLexical(name, locals!!)
        if (bind != null) {
            return bind
        }

        // Defined at toplevel (global, predeclared, universal)?
        bind = toplevel.get(name)
        if (bind != null) {
            return bind
        }
        val scope: Scope
        try {
            scope = module.resolve(name)
        } catch (ex: Module.Undefined) {
            if (!Identifier.Companion.isValid(name)) {
                // If Identifier was created by Parser.makeErrorExpression, it
                // contains misparsed text. Ignore ex and report an appropriate error.
                errorf(id, "contains syntax errors")
            } else if (ex.candidates != null) {
                // Exception provided toplevel candidates.
                // Show spelling suggestions of all symbols in scope,
                val suggestion = SpellChecker.didYouMean(name, getAllSymbols(ex.candidates))
                errorf(id, "%s%s", ex.message, suggestion)
            } else {
                errorf(id, "%s", ex.message)
            }
            return null
        }
        when (scope) {
            Scope.GLOBAL -> {
                bind = newBinding(scope, globals.size,  /* isSyntactic= */false, id)
                // Accumulate globals in module.
                globals.add(name)
            }

            Scope.PREDECLARED, Scope.UNIVERSAL -> bind =
                newBinding(scope, 0,  /* isSyntactic= */false, id) // index not used
            else -> throw IllegalStateException("bad scope: " + scope)
        }
        toplevel.put(name, bind)
        return bind
    }

    // lookupLexical finds a lexically enclosing local binding of the name,
    // plumbing it through enclosing functions as needed.
    private fun lookupLexical(name: String?, b: Block): Binding? {
        var bind = b.bindings.get(name)
        if (bind != null) {
            return bind
        }

        if (b.parent != null) {
            bind = lookupLexical(name, b.parent)
            if (bind != null) {
                // If a local binding was found in a parent block,
                // and this block is a function, then it is a free variable
                // of this function and must be plumbed through.
                // Add an implicit FREE binding (a hidden parameter) to this function,
                // and record the outer binding that will supply its value when
                // we construct the closure.
                // Also, mark the outer LOCAL as a CELL: a shared, indirect local.
                // (For a comprehension block there's nothing to do,
                // because it's part of the same frame as the enclosing block.)
                //
                // This step may occur many times if the lookupLexical
                // recursion returns through many functions.
                if (b.syntax is DefStatement || b.syntax is LambdaExpression) {
                    val scope = bind.getScope()
                    if (scope == Scope.LOCAL || scope == Scope.FREE || scope == Scope.CELL) {
                        if (scope == Scope.LOCAL) {
                            bind.scope = Scope.CELL
                        }
                        val index = b.freevars!!.size
                        b.freevars.add(bind)
                        bind = newBinding(Scope.FREE, index,  /* isSyntactic= */true, bind.first)
                    }
                }

                // Memoize, to avoid duplicate free vars and repeated walks.
                b.bindings.put(name, bind)
            }
        }

        return bind
    }

    // Common code for def, lambda.
    private fun resolveFunction(
        syntax: Node?,  // DefStatement or LambdaExpression
        name: String,
        loc: Location?,
        parameters: ImmutableList<Parameter>,
        returnType: Expression?,
        body: ImmutableList<Statement>
    ): Function {
        // Resolve parameter types and default initializer exprs in enclosing environment.

        for (param in parameters) {
            if (param is Parameter.Optional) {
                visit(param.getDefaultValue())
            }
            if (param.getType() != null && options.resolveTypeSyntax()) {
                visit(param.getType())
            }
        }
        // Resolve return type in enclosing environment.
        if (returnType != null && options.resolveTypeSyntax()) {
            visit(returnType)
        }

        // Enter function block.
        val frame = ArrayList<Binding?>()
        val freevars = ArrayList<Binding?>()
        pushLocalBlock(syntax, frame, freevars)

        // TODO: #27728 - When we handle generic type variables, they should be bound in a new outer
        // block that sits between the enclosing environment and this one. Type annotations and default
        // expressions are evaluated inside that block.

        // Check parameter order and convert to run-time order:
        // positionals, keyword-only, *args, **kwargs.
        var star: Parameter.Star? = null
        var starStar: Parameter.StarStar? = null
        var seenOptional = false
        var numKeywordOnlyParams = 0
        // TODO(adonovan): opt: when all Identifiers are resolved to bindings accumulated
        // in the function, params can be a prefix of the function's array of bindings.
        val params =
            ImmutableList.builderWithExpectedSize<Parameter?>(parameters.size)
        for (param in parameters) {
            if (param is Parameter.Mandatory) {
                // e.g. id
                if (starStar != null) {
                    errorf(
                        param,
                        "required parameter %s may not follow **%s",
                        param.getName(),
                        starStar.getName()
                    )
                } else if (star != null) {
                    numKeywordOnlyParams++
                } else if (seenOptional) {
                    errorf(
                        param,
                        "required positional parameter %s may not follow an optional parameter",
                        param.getName()
                    )
                }
                bindParam(params, param)
            } else if (param is Parameter.Optional) {
                // e.g. id = default
                seenOptional = true
                if (starStar != null) {
                    errorf(param, "optional parameter may not follow **%s", starStar.getName())
                } else if (star != null) {
                    numKeywordOnlyParams++
                }
                bindParam(params, param)
            } else if (param is Parameter.Star) {
                // * or *args
                if (starStar != null) {
                    errorf(param, "* parameter may not follow **%s", starStar.getName())
                } else if (star != null) {
                    errorf(param, "multiple * parameters not allowed")
                } else {
                    star = param
                }
            } else {
                // **kwargs
                if (starStar != null) {
                    errorf(param, "multiple ** parameters not allowed")
                }
                starStar = param as Parameter.StarStar?
            }
        }

        // * or *args
        if (star != null) {
            if (star.getIdentifier() != null) {
                bindParam(params, star)
            } else if (numKeywordOnlyParams == 0) {
                errorf(star, "bare * must be followed by keyword-only parameters")
            }
        }

        // **kwargs
        if (starStar != null) {
            bindParam(params, starStar)
        }

        createBindingsForBlock(body)
        functionDepth++
        visitAll(body)
        functionDepth--
        popLocalBlock()

        return Resolver.Function(
            name,
            loc,
            nextFunctionId++,  /* numBindingsInFile= */
            -1,  // unset for non-toplevel
            params.build(),
            body,
            star != null && star.getIdentifier() != null,
            starStar != null,
            numKeywordOnlyParams,
            frame,
            freevars,
            globals,  /* mutationFreeAtTopLevel= */
            false
        )
    }

    private fun bindParam(params: ImmutableList.Builder<Parameter?>, param: Parameter) {
        if (!bind(param.getIdentifier()!!,  /* isLoad= */false,  /* docComments= */null)) {
            errorf(param, "duplicate parameter: %s", param.getName())
        }
        params.add(param)
    }

    /**
     * Process a binding use of a name by adding a binding to the current block if not already bound,
     * and associate the identifier with it.
     * 
     * @return true if the name was newly bound in this block, or false if it already existed
     */
    private fun bind(id: Identifier, isLoad: Boolean, docComments: DocComments?): Boolean {
        val name = id.getName()
        var isNew = false
        var bind: Binding?

        // TODO(adonovan): factor out bindLocal/bindGlobal cases
        // and simply the condition below.

        // outside any function/comprehension, and not a (local) load? => global binding.
        if (locals!!.syntax is StarlarkFile && !(isLoad && !options.loadBindsGlobally())) {
            bind = toplevel.get(name)
            if (bind == null) {
                // New global binding: add to module and to toplevel cache.
                isNew = true
                bind = newBinding(Scope.GLOBAL, globals.size,  /* isSyntactic= */true, id)
                globals.add(name)
                if (docComments != null && docCommentsMap != null) {
                    docCommentsMap.put(name, docComments)
                }
                toplevel.put(name, bind)

                // Does this new global binding conflict with a file-local load binding?
                val prevLocal = locals.bindings.get(name)
                if (prevLocal != null) {
                    globalLocalConflict(id, bind.scope, prevLocal) // global, local
                }
            } else {
                toplevelRebinding(id, bind) // global, global
            }
        } else {
            // Binding is local to file, function, or comprehension.
            bind = locals.bindings.get(name)
            if (bind == null) {
                // New local binding: add to current block's bindings map, current function's frame.
                // (These are distinct entities in the case where the current block is a comprehension.)
                isNew = true
                if (locals!!.syntax is Comprehension) {
                    // Assumption: any block nested in a comprehension is either another comprehension or has
                    // its own frame (e.g. a lambda).
                    bind = newComprehensionBinding(locals.frame.size, id, syntax)
                } else {
                    bind = newBinding(Scope.LOCAL, locals.frame.size,  /* isSyntactic= */true, id)
                }
                locals.bindings.put(name, bind)
                locals.frame.add(bind)
            }

            if (isLoad) {
                // Does this (file-local) load binding conflict with a previous one?
                if (!isNew) {
                    toplevelRebinding(id, bind) // local, local
                }

                // ...or a previous global?
                val prev = toplevel.get(name)
                if (prev != null && prev.scope == Scope.GLOBAL) {
                    globalLocalConflict(id, bind.scope, prev) // local, global
                }
            }
        }

        id.setBinding(bind)

        return isNew
    }

    // Report conflicting top-level bindings of same scope, unless options.allowToplevelRebinding.
    private fun toplevelRebinding(id: Identifier, prev: Binding) {
        if (!options.allowToplevelRebinding()) {
            errorf(id, "'%s' redeclared at top level", id.getName())
            if (prev.isSyntactic) {
                errorf(prev.first, "'%s' previously declared here", id.getName())
            }
        }
    }

    // Report global/local scope conflict on top-level bindings (i.e., conflicts between globals and
    // `load()`s).
    private fun globalLocalConflict(id: Identifier, scope: Scope?, prev: Binding) {
        val newqual = if (scope == Scope.GLOBAL) "global" else "file-local"
        val oldqual = if (prev.getScope() == Scope.GLOBAL) "global" else "file-local"
        errorf(id, "conflicting %s declaration of '%s'", newqual, id.getName())
        if (prev.isSyntactic) {
            errorf(prev.first, "'%s' previously declared as %s here", id.getName(), oldqual)
        }
    }

    // Returns the union of accessible local and top-level symbols.
    private fun getAllSymbols(predeclared: MutableSet<String?>?): MutableSet<String?> {
        val all: MutableSet<String?> = HashSet<String?>()
        var b = locals
        while (b != null) {
            all.addAll(b.bindings.keys)
            b = b.parent
        }
        all.addAll(predeclared!!)
        all.addAll(toplevel.keys)
        return all
    }

    // Report an error if a load statement appears after another kind of statement.
    private fun checkLoadAfterStatement(statements: MutableList<Statement>) {
        var firstStatement: Statement? = null

        for (statement in statements) {
            // Ignore string literals (e.g. docstrings).
            if (statement is ExpressionStatement
                && statement.getExpression() is StringLiteral
            ) {
                continue
            }

            if (statement is LoadStatement) {
                if (firstStatement == null) {
                    continue
                }
                errorf(statement, "load statements must appear before any other statement")
                errorf(firstStatement, "\tfirst non-load statement appears here")
            }

            if (firstStatement == null) {
                firstStatement = statement
            }
        }
    }

    private fun pushLocalBlock(
        syntax: Node?, frame: ArrayList<Binding?>, freevars: ArrayList<Binding?>?
    ) {
        locals = Block(locals, syntax, frame, freevars)
    }

    private fun popLocalBlock() {
        locals = locals.parent
    }

    companion object {
        /**
         * Returns true if the LHS of an assignment consists purely of variable bindings (identifiers or
         * unpacked tuples/lists of identifiers). Returns false if it contains an index or dot write.
         */
        private fun isPureBinding(lhs: Expression): Boolean {
            return when (lhs) {
                -> true
                -> listExpr.getElements().stream().allMatch { lhs: Expression? -> Companion.isPureBinding(lhs!!) }
                else -> false
            }
        }

        /**
         * Performs static checks, including resolution of identifiers in `file` in the environment
         * defined by `module`. Syntax must be resolved before it is evaluated.
         * 
         * @param file file whose statements are to be resolved. Mutated by this method: [     ] nodes get bindings, resolver errors get appended to [     ][StarlarkFile.errors].
         * @param module defines predeclared variables. Not mutated. There is no requirement that this
         * object be the same as the module object used for evaluation (by [     ][net.starlark.java.eval.Starlark.execFileProgram] and friends), although they are expected
         * to have consistent behavior for [Module.resolve].
         */
        @kotlin.jvm.JvmStatic
        fun resolveFile(file: StarlarkFile, module: Module) {
            val r = Resolver(file.errors, module, file.getOptions(), file.docCommentsMap)
            var stmts = file.getStatements()

            // Check that load statements are on top.
            if (r.options.requireLoadStatementsFirst()) {
                r.checkLoadAfterStatement(stmts)
            }

            val frame = ArrayList<Binding?>()
            r.pushLocalBlock(file, frame,  /* freevars= */null)

            // First pass: creating bindings for statements in this block.
            r.createBindingsForBlock(stmts)

            // Second pass: visit all references.
            r.visitAll(stmts)

            r.popLocalBlock()

            // If the final statement is an expression, synthesize a return statement.
            val n: Int = stmts.size()
            if (n > 0 && stmts.get(n - 1) is ExpressionStatement) {
                val expr = (stmts.get(n - 1) as ExpressionStatement).getExpression()
                stmts =
                    ImmutableList.builder<Statement?>()
                        .addAll(stmts.subList(0, n - 1))
                        .add(ReturnStatement.Companion.make(expr))
                        .build()
            }

            // Annotate with resolved information about the toplevel function.
            file.setResolvedFunction(
                Resolver.Function(
                    "<toplevel>",
                    file.getStartLocation(),
                    r.nextFunctionId++,
                    r.nextBindingId,  /* params= */
                    ImmutableList.of<Parameter?>(),  /* body= */
                    stmts,  /* hasVarargs= */
                    false,  /* hasKwargs= */
                    false,  /* numKeywordOnlyParams= */
                    0,
                    frame,  /* freevars= */
                    ImmutableList.of<Binding?>(),
                    r.globals,
                    !r.sawPossibleMutationAtTopLevel
                )
            )
        }

        /**
         * Performs static checks, including resolution of identifiers in `expr` in the environment
         * defined by `module`. Syntax must be resolved before it is evaluated.
         * 
         * @param expr resolved and mutated by this method: [Identifier] nodes get bindings.
         * @param module defines predeclared variables. Not mutated. There is no requirement that this
         * object be the same as the module object used for evaluation (by [     ][net.starlark.java.eval.Starlark.execFileProgram] and friends), although they are expected
         * to have consistent behavior for [Module.resolve].
         */
        @kotlin.jvm.JvmStatic
        @Throws(SyntaxError.Exception::class)
        fun resolveExpr(expr: Expression, module: Module, options: FileOptions): Function {
            val errors: MutableList<SyntaxError?> = ArrayList<SyntaxError?>()
            val r = Resolver(errors, module, options,  /* docCommentsMap= */null)

            val frame = ArrayList<Binding?>()
            r.pushLocalBlock(null, frame,  /* freevars= */null) // for bindings in list comprehensions
            r.visit(expr)
            r.popLocalBlock()

            if (!errors.isEmpty()) {
                throw SyntaxError.Exception(errors)
            }

            // Return no-arg function that computes the expression.
            return Resolver.Function(
                "<expr>",
                expr.getStartLocation(),
                r.nextFunctionId++,
                r.nextBindingId,  /* params= */
                ImmutableList.of<Parameter?>(),
                ImmutableList.of<Statement?>(ReturnStatement.Companion.make(expr)),  /* hasVarargs= */
                false,  /* hasKwargs= */
                false,  /* numKeywordOnlyParams= */
                0,
                frame,  /* freevars= */
                ImmutableList.of<Binding?>(),
                r.globals,
                !r.sawPossibleMutationAtTopLevel
            )
        }
    }
}
